### ISSUE TITLE
I want to Contribute 

### ISSUE THREAD

**Issue by minhaj-313** [almirpask/Hacktoberfest-Tasks#55]

**Comment by almirpask** [comment]
@minhaj-313 hi, read the instructions on the [README.md](https://github.com/almirpask/Hacktoberfest-Tasks/blob/main/README.md) and send your pull requests. Tell me if you still have questions about how to do this ok.

**Comment by minhaj-313** [comment]
> @minhaj-313 hi, read the instructions on the [README.md](https://github.com/almirpask/Hacktoberfest-Tasks/blob/main/README.md) and send your pull requests. Tell me if you still have questions about how to do this ok.

Please Merge My PR by Labeling hacktoberfest-accepted. 
I did sent you a PR.

**Comment by almirpask** [comment]
@minhaj-313 your pr is merged, consider give a star to this project :)

**Comment by minhaj-313** [comment]
@almirpask Yeah Sure i did,
atleast you label it. otherwise it not be counted for hacktoberfest
Thanks Again.
